// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT8nOgb8-xwEBCsbVpdeP1PzkDpRpcj3o',
    appId: '1:892602934255:web:bcba2772590bdac2cd4c1a',
    messagingSenderId: '892602934255',
    projectId: 'automationbrilliance-161c1',
    authDomain: 'automationbrilliance-161c1.firebaseapp.com',
    databaseURL: 'https://automationbrilliance-161c1-default-rtdb.firebaseio.com',
    storageBucket: 'automationbrilliance-161c1.appspot.com',
    measurementId: 'G-0LHP4VTMRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtJkAAEVbEDngPAvOhpfCX0eYqj3gwiYU',
    appId: '1:892602934255:android:d51be30562d79563cd4c1a',
    messagingSenderId: '892602934255',
    projectId: 'automationbrilliance-161c1',
    databaseURL: 'https://automationbrilliance-161c1-default-rtdb.firebaseio.com',
    storageBucket: 'automationbrilliance-161c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_QV7yPIVzLUVQmTO_v-9jwu7DJQEg57Q',
    appId: '1:892602934255:ios:a925d28e31a4e59ecd4c1a',
    messagingSenderId: '892602934255',
    projectId: 'automationbrilliance-161c1',
    databaseURL: 'https://automationbrilliance-161c1-default-rtdb.firebaseio.com',
    storageBucket: 'automationbrilliance-161c1.appspot.com',
    iosBundleId: 'com.example.automationBrillianceHomepage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_QV7yPIVzLUVQmTO_v-9jwu7DJQEg57Q',
    appId: '1:892602934255:ios:a925d28e31a4e59ecd4c1a',
    messagingSenderId: '892602934255',
    projectId: 'automationbrilliance-161c1',
    databaseURL: 'https://automationbrilliance-161c1-default-rtdb.firebaseio.com',
    storageBucket: 'automationbrilliance-161c1.appspot.com',
    iosBundleId: 'com.example.automationBrillianceHomepage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT8nOgb8-xwEBCsbVpdeP1PzkDpRpcj3o',
    appId: '1:892602934255:web:b84c0af1148c75b9cd4c1a',
    messagingSenderId: '892602934255',
    projectId: 'automationbrilliance-161c1',
    authDomain: 'automationbrilliance-161c1.firebaseapp.com',
    databaseURL: 'https://automationbrilliance-161c1-default-rtdb.firebaseio.com',
    storageBucket: 'automationbrilliance-161c1.appspot.com',
    measurementId: 'G-G903T0Q792',
  );

}